# This file is where you define your pipelines. You can define multiple.
# For more information on multiple pipelines, see the documentation:
#   https://www.elastic.co/guide/en/logstash/current/multiple-pipelines.html
#   https://www.elastic.co/guide/en/logstash/current/logstash-settings-file.html
#   https://github.com/elastic/logstash/issues/6926

- pipeline.id: pipeline_main
  path.config: "/usr/share/logstash/pipeline"

- pipeline.id: pipeline_business
  path.config: "/usr/share/logstash/pipeline_business/conf.d/*.conf"
  # path.config: "/usr/share/logstash/pipeline_business/*.conf"
  queue.type: persisted
  dead_letter_queue.enable: true
  dead_letter_queue.max_bytes: 1024mb
  # path.dead_letter_queue: path.data/dlq_business

- pipeline.id: pipeline_devops
  path.config: "/usr/share/logstash/pipeline_devops/**/*.conf"
  queue.type: persisted
  dead_letter_queue.enable: true
  dead_letter_queue.max_bytes: 1024mb
  # path.dead_letter_queue: path.data/dlq_devops